### PR TITLE
Add expiration to response of GetCertificateCredentials

### PR DESCRIPTION
**Pull request by Marusyk**
After generation it would be nice to return expiration value. I need to store that and show notifications. Please review

### CODE REVIEW

**Comment by Marusyk** [comment]
Any news? When it can be merged?

**Comment by Marusyk** [comment]
ping

**Comment by Marusyk** [comment]
ping

**Comment by Marusyk** [comment]
@rajanadar Is this project dead?

**Comment by roederja2** [comment]
Maybe you need to set up a fork...

**Comment by Marusyk** [comment]
I did, but I don't want to publish my own package with this small fix.

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by seif** [comment]
@Marusyk it is a real shame @rajanadar is not able to handle these issues/ prs in a timely manner. @rajanadar really, add more contributors.

**Comment by hoerup** [comment]
> 
> 
> @Marusyk it is a real shame @rajanadar is not able to handle these issues/ prs in a timely manner. @rajanadar really, add more contributors.
I have tried reaching out to @rajanadar but no luck so far :(

**Comment by hoerup** [comment]
Unfortunately, it seems like the only way to get this project moving forward is to make a fork  :(

**Pull request closed without merging**
