### PR TITLE
fix gh-238 : Add Entity Endpoints for Identity Secret Engine

### PR DESCRIPTION
**Pull request by konidev20**
### Changelog
- Added entity endpoints for Identity Secrets Engine

### Github Issue
gh-238

### CODE REVIEW

**Comment by konidev20** [comment]
@rajanadar can you review all the entity endpoints after new year's? We can close this PR and get additional endpoints as and when required.

**Comment by rajanadar** [comment]
@konidev20  Thanks for all the support. Let me know if you'll finish this PR or if you want me to take over and finish it. Am fine, either ways. Let me know by 7/25

**Comment by konidev20** [comment]
Hey @rajanadar, 

Welcome back. 

I will review the changes I had made on the weekend. I opened this PR a long time ago. 

I will test the endpoints and let you know about it.

**Comment by rajanadar** [comment]
Thanks @konidev20.

It is already an awesome pr. So feel free to compete it and transition over with whatever checkpoint.

**Comment by konidev20** [comment]
Hey @rajanadar, 

I've reviewed the changes. I see this adds all the APIs required for an entity in the Identity Secrets Engine. 

API Reference: https://www.vaultproject.io/api-docs/secret/identity/entity

**Pull request merged**
