### PR TITLE
Add possibility to revoke certificate

### PR DESCRIPTION
**Pull request by Marusyk**
We need that possibility. Please review 

Thank you in advance

### CODE REVIEW

**Comment by Marusyk** [comment]
It would be great to know when it can be reviewed and what do you think. If it has low priority for you then I will use my forked project. because I need that for the next week. Thx

**Comment by rajanadar** [comment]
Let me look at this in a couple of days.

**Comment by Marusyk** [comment]
Ok, thanks

**Comment by Marusyk** [comment]
I'm going to close this PR. I use simple httpclient to do that

**Comment by Marusyk** [comment]
@rajanadar Please provide some information. Should I wait or use something else?

**Comment by Marusyk** [comment]
@rajanadar Please review

**Comment by Marusyk** [comment]
@rajanadar  ping

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by rajanadar** [comment]
Hey, I'll have a look this week. Sorry for the radio silence. Had to be oof for a couple of weeks on the personal front.

**Comment by Marusyk** [comment]
this week?

**Comment by Marusyk** [comment]
@rajanadar What about "I'll have a look this week"?

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by Marusyk** [comment]
@rajanadar still waiting

**Comment by Marusyk** [comment]
@rajanadar when you will be able to merge this?

**Comment by Marusyk** [comment]
@rajanadar are you kidding?

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by Marusyk** [comment]
@rajanadar ping

**Comment by rajanadar** [comment]
@Marusyk , i have absorbed your PR in the latest master branch.

**Comment by Marusyk** [comment]
@rajanadar Why it is not merged with saving code author?

**Comment by rajanadar** [comment]
@Marusyk  I had a lot of local changes from last year that I had to work through for the last week, clean it up. This feature was already in there 90%. 

Once I publish 0.11.x in 2 days, I want to have a fresh clean start on the Issues (with clear next release triaged issues).

**Comment by rajanadar** [comment]
Please pardon the adhoc-issue-fixes till then.

**Pull request closed without merging**
