### PR TITLE
Feature - Add method to destroys a secret for a specified location.

### PR DESCRIPTION
**Pull request by simedbn**
This feature is about deleting a secret and it's all versions permanently.

BR.

### CODE REVIEW

**Comment by Marusyk** [comment]
related #84

**Comment by tovapatel** [comment]
When can we expect the new version available for public use ?

**Comment by Marusyk** [comment]
as I see, not soon

@rajanadar is not responding

**Comment by tovapatel** [comment]
Thanks @Marusyk : Can you please confirm here we are discussing the same issue where the DestroySecretAsync API only removes the Secret data but the actual file still exists.. correct ?

**Comment by rajanadar** [comment]
thanks @simedbn .
This feature got in from my other commits.

**Pull request closed without merging**
