### PR TITLE
Replace Newtonsoft JSON with System.Text.Json

### PR DESCRIPTION
**Pull request by rajanadar**
Build is successful. 
Testing in progress.

### CODE REVIEW

**Comment by rajanadar** [comment]
@vadimkhm @digitalray

**Comment by vadimkhm** [comment]
> @vadimkhm @digitalray

Hi, @rajanadar hope you are well, any news?

**Comment by rajanadar** [comment]
Hey all good. Testing in progress. Fixing issues one after other for enum readers, json property name changes, type converters etc.

Will have another checkpoint in 2-3 days.

**Comment by rajanadar** [comment]
@vadimkhm . All the test cases passed. There is a bizarre case of a Hmac verification passing in master branch and not passing in this branch with same keys. I'll look into it later.

For the moment, can you please take a library reference from this branch and let me know if everything is successful at your side?

If yes, then i'll publish a beta nuget package for you.

**Comment by vadimkhm** [comment]
> @vadimkhm . All the test cases passed. There is a bizarre case of a Hmac verification passing in master branch and not passing in this branch with same keys. I'll look into it later.
> 
> For the moment, can you please take a library reference from this branch and let me know if everything is successful at your side?
> 
> If yes, then i'll publish a beta nuget package for you.

Thank you very much!!!, cool, I will start integration :)

**Comment by rajanadar** [comment]
> @vadimkhm . All the test cases passed. There is a bizarre case of a Hmac verification passing in master branch and not passing in this branch with same keys. I'll look into it later.
> 
> For the moment, can you please take a library reference from this branch and let me know if everything is successful at your side?
> 
> If yes, then i'll publish a beta nuget package for you.

The hmac issue is also fixed. Apparently, Vault behaves differently if certain fields are not passed at all in JSON vs. passed as null, which is very strange. Adding the IgnoreOnNull behavior to json serialization to those fields fixed the issue.

**Comment by vadimkhm** [comment]
Hi @rajanadar we created a local nuget and all is good for now, thank you

**Comment by rajanadar** [comment]
> Hi @rajanadar we created a local nuget and all is good for now, thank you

Glad to hear @vadimkhm. Let me know if you need a beta nuget for it officially.

I am anyways inspecting version support and if all looks well, I may change the master branch to this and publish an official version as well without Newtonsoft Json.

**Pull request merged**
