### PR TITLE
updated changelog

### PR DESCRIPTION
**Pull request by hoerup**

### CODE REVIEW

**Review by Marusyk — APPROVED** [review]
Today will be released the new version?
Can anyone other than @rajanadar do this?

**Comment by hoerup** [comment]
Well, since i dont have access to the AppVeyor settings I don't know if he has set up tag/release builds - so there's only one way to find out :)

**Comment by hoerup** [comment]
Nope :( no release and publish workflow in AppVeyor

**Comment by hoerup** [comment]
There's not even published any artifacts from CI

**Pull request merged**
