### PR TITLE
Generatedatakey

### PR DESCRIPTION
**Pull request by RafaelMontegordoFelix**
Hi there, i added the Generate Data Key option in secrets/transit.

### CODE REVIEW

**Comment by rajanadar** [comment]
thanks @RafaelMontegordoFelix . 

Do you need this functionality immediately? If yes, i can publish a new version. If not, we can wait till the next batch.
Let me know.

**Comment by RafaelMontegordoFelix** [comment]
Hello,
It was nice if you could publish a new version of the package.
I am finishing a pci compliance project and I really need that feature.
Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rajanadar** [comment]
cool. i have published a new version 1.4.0.5. Let me know if any issues.
Please note that i switched the parameter order from keyname, keytype to keytype, keyname. Be aware.

Good luck with your PCI.

**Comment by RafaelMontegordoFelix** [comment]
Ok, that's better yes.
Thank you.

**Pull request merged**
