### PR TITLE
Additional Token and Encryption Key Management Functionality

### PR DESCRIPTION
**Pull request by irvingd**
Needed to add functionality required in a project using VaultSharp

- Added support to query the details of a token
- Added support to create, read, update, and delete encryption key
- Added support to rotate an encryption key
- Added support to rewrap data with a new version of an encryption key
- Added additional encryption key

### CODE REVIEW

**Comment by rajanadar** [comment]
thanks for this @irvingd 
I'll merge and release a version by new year

**Review by rajanadar — APPROVED** [review]

**Comment by rajanadar** [comment]
@irvingd  i published the new version with changes.
let me know https://www.nuget.org/packages/VaultSharp/1.6.0.2

**Comment by irvingd** [comment]
@rajanadar - thanks! I will switch our project to use the updated Nuget and let you know if there are any issues.

cheers!

ps: I will be adding submitting additional PR's to surface additional methods from the Vault API. I'm also working on an xunit-based project for adding tests

**Comment by rajanadar** [comment]
Thanks @irvingd.

Great to hear on additional apis. Also let me know your requirements in case you are pressed for time. I refrain from the administrative apis till there is a need.

As for the xunit tests, please don't spend time on it. The value add is not great on it. I would rather spend time on Program.cs to test the real flow rather than unit tests. All vault apis have a pattern of request payload serialization, an endpoint and response deser. Unit tests don't add any value here. So I would recommend that you don't spend time on it at all. Instead, program.cs is a better investment. 

Program.cs works in 2 ways. After the initial manual start of vault server, you can run program.cs in an automated manner 100%. It emits a Program Output.txt file in the debug directory to help you see our pojo json vs actual json, and if the stuff works end to end. This is one way. The second way is a manual way where I pause the execution somewhere in program.cs and then test db plug-ins, kerberos etc. The weird ones.
Backends like token, transit etc. are easy for automation. Hence my suggestion.

**Pull request merged**
