### PR TITLE
feat : added create, read, list & delete token role APIs

### PR DESCRIPTION
**Pull request by konidev20**
Feature Request : #245 

Summary:
- Added required models and request objects for the APIs following the documentation [https://www.vaultproject.io/api/auth/token#create-update-token-role]

Request for Review : @rajanadar

### CODE REVIEW

**Comment by hoerup** [comment]
@rajanadar  what's your thought on implementing LIST as a non-standard http verb

Everywhere else in the codebase you use the `?list=true`

**Comment by konidev20** [comment]
> @rajanadar  what's your thought on implementing LIST as a non-standard http verb
> 
> Everywhere else in the codebase you use the `?list=true`
> 

Hey just checked the official API documentation of HashiCorp Vault APIs. 

I wasn't aware of the usage of `HTTP GET` with Query parameter `?list=true`.

@hoerup do you recommend I revert those changes? I'd like to keep the convention same as other list APIs to ensure maintainability.

Thanks for the review 👊🏻

**Comment by konidev20** [comment]
@hoerup please review if the changes are in order.

**Review by hoerup — APPROVED** [review]
LGTM

**Comment by rajanadar** [comment]
thanks both.

**Pull request merged**
