### PR TITLE
Copy IDictionary into Dictionary to remove infinite recursion

### PR DESCRIPTION
**Pull request by vader1986**
I run into a problem that VaultSharp was just hanging when I tried to write a secret. I believe this is a reason (VS 2019/ReSharper should also give you a warning about this).

### CODE REVIEW

**Comment by vader1986** [comment]
Saying that, I'm not sure this method is need at all. Just directly calling the generic method will work anyway.

**Comment by rajanadar** [comment]
thanks @vader1986 

Hey Timm, can you please let me know if you still have this issue? And what is your second comment above? is this still needed?

**Comment by vader1986** [comment]
> thanks @vader1986
> 
> Hey Timm, can you please let me know if you still have this issue? And what is your second comment above? is this still needed?

I think this is still an issue, even though I worked around it, as mentioned above by directly calling the generic method. The problem with this method is that it is calling itself recursively, which leads to an infinite loop:

```
public async Task<Secret<Dictionary<string, object>>> WriteSecretAsync(string path, IDictionary<string, object> values, string mountPoint)
{
    return await WriteSecretAsync(path, values, mountPoint);
}
```

As I'm avoiding this problem by not calling this method, I only raised this PR in case other people run into this problem.

**Comment by rajanadar** [comment]
Got it. Thanks for explaining. I'll get this in.

**Review by rajanadar — APPROVED** [review]

**Comment by rajanadar** [comment]
https://www.nuget.org/packages/VaultSharp/1.4.0.7

**Pull request merged**
