### PR TITLE
Make Polymath and VaultClient disposable in order to cleanup httpclient

### LINKED ISSUE #99: Add Disposable to VaultClient (and PolyMath)
Deep inside VaultClient there is a Disposable HttpClient instance, but via normal usage, there is now way to force a Dispose of that client object.

### PR DESCRIPTION
**Pull request by hoerup**
Resolved #99

### CODE REVIEW

**Comment by mortenmoulder** [comment]
@rajanadar any update when this might get merged? Could really be useful for us.

**Comment by rajanadar** [comment]
@hoerup  can we have a little more discussion on this. 
https://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed-between-requests

**Comment by rajanadar** [comment]
@hoerup  based on https://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed-between-requests

I am closing this PR, since the summary recommendation is to not worry about disposing it

**Comment by hoerup** [comment]
Not a big deal anymore, after HttpClient can be injected. So if user wants to control lifecycle of httpclient then it's possible that way

**Pull request closed without merging**
